import './css/style.css';

import { Inter } from 'next/font/google';
import { Space_Grotesk } from 'next/font/google';
import localFont from 'next/font/local';

import Header from '@/components/ui/header';
import SmoothScrolling from '../components/smooth-scroll';
import Script from 'next/script';

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-inter',
	display: 'swap',
});

const grotek = Space_Grotesk({
	subsets: ['latin'],
	variable: '--font-grotesk',
	display: 'swap',
});

const nacelle = localFont({
	src: [
		{
			path: '../public/fonts/nacelle-regular.woff2',
			weight: '400',
			style: 'normal',
		},
		{
			path: '../public/fonts/nacelle-italic.woff2',
			weight: '400',
			style: 'italic',
		},
		{
			path: '../public/fonts/nacelle-semibold.woff2',
			weight: '600',
			style: 'normal',
		},
		{
			path: '../public/fonts/nacelle-semibolditalic.woff2',
			weight: '600',
			style: 'italic',
		},
	],
	variable: '--font-nacelle',
	display: 'swap',
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body
				className={`${inter.variable} ${nacelle.variable} ${grotek.variable} bg-[#0B0C14] font-grotesk text-base text-gray-200 antialiased`}
			>
				{/* #00031a */}
				<SmoothScrolling>
					<div className='flex min-h-screen flex-col overflow-hidden supports-[overflow:clip]:overflow-clip'>
						<Header />
						{children}
					</div>
				</SmoothScrolling>
				<Script
					id='voiceflow-chat-widget'
					type='text/javascript'
					strategy='lazyOnload' // Ensures the script loads after the page content
				>
					{`
          (function(d, t) {
            var v = d.createElement(t), s = d.getElementsByTagName(t)[0];
            v.onload = function() {
              window.voiceflow.chat.load({
                verify: { projectID: '66207aa2befcd3484056d86a' },
                url: 'https://general-runtime.voiceflow.com',
                versionID: 'production'
              });
            }
            v.src = "https://cdn.voiceflow.com/widget/bundle.mjs"; 
            v.type = "text/javascript"; 
            s.parentNode.insertBefore(v, s);
          })(document, 'script');
        `}
				</Script>
			</body>
		</html>
	);
}
